[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { RAILWAY_ENVIRONMENT = "production" }
