[build]
builder = "nixpacks"
buildCommand = "./railway-build.sh"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { RAILWAY_ENVIRONMENT = "production" }
