[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { 
  RAILWAY_ENVIRONMENT = "production",
  SPRING_PROFILES_ACTIVE = "production"
}
