package com.yakrooms.be.model.enums;

public enum NotificationType {
	BOOKING, REMINDER, ADMIN_ALERT, BOOKING_CONFIRMATION, BOOKING_CREATED, BOOKING_CANCELLATION_REQUEST, BOOKING_CANCELLATION_REJECTED
}
